---

version: '3.8'

networks:
  my_network:
    driver: bridge
    external: false

services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/:delegated
      - .docker/nginx-templates/default.conf.tmpl:/etc/nginx/conf.d/default.conf
    networks:
      - my_network
    environment:
      PHP_URL: php-fpm:9000
      NGINX_LISTNER_PORT: 80

  php-fpm:
    container_name: php-fpm
    hostname: php-fpm
    volumes:
      - ./:/var/www/:delegated
    build:
      context: .
      dockerfile: .docker/Dockerfile
      target: base-dev
    networks:
      my_network:
        aliases:
          - my-php-fpm
    extra_hosts:
      - "host.docker.internal:host-gateway"

  php-fpm-test:
    container_name: php-fpm-test
    hostname: php-fpm-test
    volumes:
      - ./:/var/www/:delegated
    build:
      context: .
      dockerfile: .docker/Dockerfile
      target: base-dev
    networks:
      my_network:
        aliases:
          - my-php-fpm
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      APP_ENV: test

  redis:
    container_name: redis
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    networks:
      my_network:
        aliases:
          - my-redis
    volumes:
      - redis:/data

volumes:
  redis:
    driver: local