openapi: 3.0.3

info:
  title: Statistic app
  description: Statistic app api
  version: 1.0.0

tags:
  - name: Country
    description: Страны

paths:
  /api/statistics/countries:
    get:
      tags:
        - Country
      summary: "Получение списка статистики по странам"
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CountryListResponse'

    post:
      tags:
        - Country
      summary: "Обновление инкремента по конкретной стране"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              required:
                - code
              properties:
                code:
                  type: string
                  minimum: 2
                  maximum: 2
                  pattern: '^[A-Z]{2}$'
                  example: "RU"
      responses:
        '204':
          description: Successful response
        '422':
          description: Unprocessable Content
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JsonError'

components:
  schemas:
    CountryListResponse:
      type: object
      example:
        "RU": "1"
        "US": "2"
        "GB": "3"

    JsonError:
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              status:
                type: integer
              title:
                type: string
              detail:
                type: string
